project:
  type: website
  output-dir: docs

website:
  title: "isl_web"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/chadyuu/isl-web/
    contents:
      - index.qmd
      - 4.classification.qmd
      - 5.resampling.qmd
      - 6.model-selection.qmd
      - 7.beyond-linearity.qmd
      - 8.tree-based.qmd
      - 9.support-vector-machine.qmd
      - 12.unsupervised.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

